"""
apps/vouchers/models.py
-----------------------
Prepaid voucher system.
Admins generate VoucherBatches; each Batch produces N individual Vouchers.
A subscriber redeems a voucher code at the captive portal to activate a plan.
"""

import secrets
import string
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from utils.mixins import BaseModel
from utils.validators import validate_voucher_code, validate_positive_integer


def _generate_voucher_code() -> str:
    """Generate a unique TGD-XXXX-XXXX code (uppercase alphanumeric)."""
    alphabet = string.ascii_uppercase + string.digits
    part1 = "".join(secrets.choice(alphabet) for _ in range(4))
    part2 = "".join(secrets.choice(alphabet) for _ in range(4))
    return f"TGD-{part1}-{part2}"


class VoucherBatch(BaseModel):
    """
    A named batch of vouchers generated in one admin action.
    Tracks how many were generated, redeemed, and voided.
    """

    name = models.CharField(
        max_length=120,
        verbose_name=_("Batch Name"),
        help_text=_("Descriptive label, e.g. 'June 2026 Monthly 50GB'."),
    )
    plan = models.ForeignKey(
        "subscriptions.Plan",
        on_delete=models.PROTECT,
        related_name="voucher_batches",
        verbose_name=_("Plan"),
    )
    quantity = models.PositiveIntegerField(
        validators=[validate_positive_integer],
        verbose_name=_("Quantity"),
        help_text=_("Number of voucher codes to generate."),
    )
    valid_from = models.DateTimeField(
        verbose_name=_("Valid From"),
    )
    valid_until = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Valid Until"),
        help_text=_("Leave blank for no expiry date on unredeemed codes."),
    )
    generated_by = models.ForeignKey(
        "accounts.AdminUser",
        null=True,
        on_delete=models.SET_NULL,
        related_name="generated_batches",
        verbose_name=_("Generated By"),
    )
    notes = models.TextField(blank=True, verbose_name=_("Notes"))

    class Meta:
        db_table = "vouchers_batch"
        ordering = ["-created_at"]
        verbose_name = _("Voucher Batch")
        verbose_name_plural = _("Voucher Batches")

    def __str__(self):
        return f"Batch: {self.name} ({self.quantity} codes)"

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def clean(self):
        self.name = self.name.strip()

        if not self.name:
            raise ValidationError({"name": _("Batch name cannot be blank.")})

        if self.quantity > 10_000:
            raise ValidationError(
                {"quantity": _("Cannot generate more than 10,000 vouchers in a single batch.")}
            )

        if self.valid_until and self.valid_from:
            if self.valid_until <= self.valid_from:
                raise ValidationError(
                    _("Valid-until date must be after the valid-from date.")
                )

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    # ------------------------------------------------------------------
    # Stats helpers (computed, not stored — avoids race conditions)
    # ------------------------------------------------------------------

    @property
    def redeemed_count(self) -> int:
        return self.vouchers.filter(status=Voucher.VoucherStatus.REDEEMED).count()

    @property
    def available_count(self) -> int:
        return self.vouchers.filter(status=Voucher.VoucherStatus.UNUSED).count()

    @property
    def voided_count(self) -> int:
        return self.vouchers.filter(status=Voucher.VoucherStatus.VOIDED).count()


class Voucher(BaseModel):
    """
    An individual prepaid voucher code.

    Lifecycle: UNUSED → REDEEMED (on first successful redemption)
              UNUSED → EXPIRED  (if the batch expiry date passes)
              UNUSED → VOIDED   (admin action)
    """

    class VoucherStatus(models.TextChoices):
        UNUSED = "unused", _("Unused")
        REDEEMED = "redeemed", _("Redeemed")
        EXPIRED = "expired", _("Expired")
        VOIDED = "voided", _("Voided")

    batch = models.ForeignKey(
        VoucherBatch,
        on_delete=models.CASCADE,
        related_name="vouchers",
        verbose_name=_("Batch"),
    )
    code = models.CharField(
        max_length=14,
        unique=True,
        default=_generate_voucher_code,
        validators=[validate_voucher_code],
        verbose_name=_("Voucher Code"),
    )
    status = models.CharField(
        max_length=20,
        choices=VoucherStatus.choices,
        default=VoucherStatus.UNUSED,
        db_index=True,
        verbose_name=_("Status"),
    )
    redeemed_by = models.ForeignKey(
        "subscribers.Subscriber",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="redeemed_vouchers",
        verbose_name=_("Redeemed By"),
    )
    redeemed_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Redeemed At"),
    )
    voided_by = models.ForeignKey(
        "accounts.AdminUser",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="voided_vouchers",
        verbose_name=_("Voided By"),
    )
    void_reason = models.TextField(
        blank=True,
        verbose_name=_("Void Reason"),
    )

    class Meta:
        db_table = "vouchers_voucher"
        ordering = ["code"]
        verbose_name = _("Voucher")
        verbose_name_plural = _("Vouchers")
        indexes = [
            models.Index(fields=["code"], name="idx_voucher_code"),
            models.Index(fields=["status"], name="idx_voucher_status"),
        ]

    def __str__(self):
        return f"{self.code} [{self.status}]"

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def clean(self):
        self.code = self.code.strip().upper()

        # Redeemed voucher must have subscriber and timestamp
        if self.status == self.VoucherStatus.REDEEMED:
            if not self.redeemed_by_id:
                raise ValidationError(
                    _("A redeemed voucher must reference the subscriber who redeemed it.")
                )
            if not self.redeemed_at:
                raise ValidationError(
                    _("A redeemed voucher must have a redemption timestamp.")
                )

        # Voided voucher must have a reason
        if self.status == self.VoucherStatus.VOIDED and not self.void_reason:
            raise ValidationError(
                {"void_reason": _("Please provide a reason when voiding a voucher.")}
            )

        # Once redeemed, status should not change
        if self.pk:
            old = Voucher.objects.filter(pk=self.pk).values_list("status", flat=True).first()
            if old == self.VoucherStatus.REDEEMED and self.status != self.VoucherStatus.REDEEMED:
                raise ValidationError(
                    _("A redeemed voucher cannot change status.")
                )

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    # ------------------------------------------------------------------
    # Business helpers
    # ------------------------------------------------------------------

    @property
    def is_redeemable(self) -> bool:
        """True only when the code can still be used."""
        from django.utils import timezone
        if self.status != self.VoucherStatus.UNUSED:
            return False
        batch_expired = (
            self.batch.valid_until is not None
            and self.batch.valid_until < timezone.now()
        )
        return not batch_expired

    def redeem(self, subscriber) -> None:
        from django.utils import timezone

        if not self.is_redeemable:
            raise ValidationError(_("This voucher code is not available for redemption."))

        self.status = self.VoucherStatus.REDEEMED
        self.redeemed_by = subscriber
        self.redeemed_at = timezone.now()
        self.save(update_fields=["status", "redeemed_by", "redeemed_at", "updated_at"])

    def void(self, admin, reason: str) -> None:
        if self.status != self.VoucherStatus.UNUSED:
            raise ValidationError(_("Only unused vouchers can be voided."))

        self.status = self.VoucherStatus.VOIDED
        self.voided_by = admin
        self.void_reason = reason
        self.save(update_fields=["status", "voided_by", "void_reason", "updated_at"])