"""
apps/reporting/admin.py
------------------------
Django admin for analytics dashboards, revenue summaries, and subscriber reports.
All reporting data is read-only — generated by Celery Beat tasks.
"""

from django.contrib import admin
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _

from .models import DashboardMetrics, RevenueSummary, SubscriberReport


@admin.register(DashboardMetrics)
class DashboardMetricsAdmin(admin.ModelAdmin):
    list_display = (
        "metrics_date", "active_subscribers", "online_now",
        "sessions_today", "revenue_usd",
        "total_traffic_gb", "fraud_alerts", "created_at",
    )
    date_hierarchy = "metrics_date"
    ordering = ("-metrics_date",)
    readonly_fields = tuple(
        f.name for f in DashboardMetrics._meta.get_fields()
        if hasattr(f, "name") and not f.many_to_many
    )

    fieldsets = (
        (_("Date"), {"fields": ("metrics_date",)}),
        (_("Subscribers"), {
            "fields": (
                "total_subscribers", "active_subscribers", "expired_subscribers",
                "suspended_subscribers", "new_subscribers_today", "churned_subscribers",
            ),
        }),
        (_("Sessions"), {
            "fields": ("online_now", "sessions_today", "avg_session_minutes"),
        }),
        (_("Traffic"), {
            "fields": ("total_upload_gb", "total_download_gb", "total_traffic_gb", "peak_hour"),
        }),
        (_("Quota"), {
            "fields": ("quota_exceeded_count", "quota_warned_count"),
        }),
        (_("Revenue"), {
            "fields": ("revenue_usd", "new_plans_sold", "renewals_today", "vouchers_redeemed"),
        }),
        (_("Errors & Fraud"), {
            "fields": ("failed_logins", "fraud_alerts", "system_errors"),
        }),
        (_("Devices & Admin"), {
            "fields": ("unique_devices", "device_changes_requested", "admin_actions_today"),
        }),
    )

    def has_add_permission(self, request):
        return False  # Generated by Celery Beat — do not create manually

    def has_change_permission(self, request, obj=None):
        return False


@admin.register(RevenueSummary)
class RevenueSummaryAdmin(admin.ModelAdmin):
    list_display = (
        "summary_date", "monthly_revenue", "total_transactions",
        "new_subscriptions", "renewed_subscriptions", "cancelled_subscriptions",
    )
    date_hierarchy = "summary_date"
    ordering = ("-summary_date",)
    readonly_fields = tuple(
        f.name for f in RevenueSummary._meta.get_fields()
        if hasattr(f, "name") and not f.many_to_many
    )

    fieldsets = (
        (_("Period"), {"fields": ("summary_date",)}),
        (_("Revenue"), {
            "fields": ("daily_revenue", "weekly_revenue", "monthly_revenue"),
        }),
        (_("By Plan Type"), {
            "fields": ("daily_plan_revenue", "weekly_plan_revenue",
                       "monthly_plan_revenue", "custom_plan_revenue"),
        }),
        (_("Transactions"), {
            "fields": ("total_transactions", "successful_transactions", "failed_transactions"),
        }),
        (_("Subscriptions"), {
            "fields": ("new_subscriptions", "renewed_subscriptions", "cancelled_subscriptions"),
        }),
    )

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False


@admin.register(SubscriberReport)
class SubscriberReportAdmin(admin.ModelAdmin):
    list_display = (
        "subscriber", "report_period_start", "report_period_end",
        "total_gb_display", "total_spent_usd",
        "sessions_count", "is_sent", "generated_at",
    )
    list_filter = ("is_sent",)
    search_fields = ("subscriber__username", "subscriber__full_name")
    date_hierarchy = "generated_at"
    ordering = ("-generated_at",)
    readonly_fields = tuple(
        f.name for f in SubscriberReport._meta.get_fields()
        if hasattr(f, "name") and not f.many_to_many
    )
    raw_id_fields = ("subscriber",)

    fieldsets = (
        (_("Report"), {
            "fields": ("subscriber", "report_period_start", "report_period_end", "generated_at"),
        }),
        (_("Activity"), {
            "fields": ("sessions_count", "total_session_hours", "last_active_at"),
        }),
        (_("Usage"), {
            "fields": ("upload_gb", "download_gb", "total_gb", "quota_limit_gb", "quota_usage_percent"),
        }),
        (_("Spending"), {
            "fields": ("plans_active", "renewals_count", "total_spent_usd"),
        }),
        (_("Alerts"), {
            "fields": ("quota_warnings", "failed_logins", "fraud_alerts"),
        }),
        (_("Delivery"), {
            "fields": ("is_sent", "sent_at"),
        }),
    )

    def has_add_permission(self, request):
        return False  # Reports are generated via API action or Celery task

    def has_change_permission(self, request, obj=None):
        return False

    @admin.display(description=_("Total Used"))
    def total_gb_display(self, obj):
        return format_html("{:.2f} <small>GB</small>", obj.total_gb)
