"""
apps/reporting/views.py
------------------------
Analytics dashboard, revenue summaries, and per-subscriber reports.
All reporting is read-only — data is generated by Celery Beat tasks.
"""

from django.utils import timezone
from rest_framework import status, filters
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ReadOnlyModelViewSet

from .models import DashboardMetrics, RevenueSummary, SubscriberReport
from .serializers import (
    DashboardMetricsSerializer,
    RevenueSummarySerializer,
    RevenueSummaryListSerializer,
    SubscriberReportListSerializer,
    SubscriberReportDetailSerializer,
    ReportingFilterSerializer,
)


class DashboardView(APIView):
    """
    GET /api/v1/reporting/dashboard/
    Returns real-time dashboard metrics formatted exactly as the React frontend expects
    (flat camelCase object matching the ADMIN_STATS mock) for the best UI/UX out of the box.
    """

    permission_classes = [IsAuthenticated, IsAdminUser]

    def get(self, request, *args, **kwargs):
        from django.db.models import Sum
        from decimal import Decimal

        from apps.subscribers.models import Subscriber
        from apps.accounting.models import Session
        from apps.subscriptions.models import Subscription
        from apps.devices.models import DeviceChangeRequest
        from apps.fraud.models import FraudAlert
        from apps.quota.models import DailyQuotaUsage

        today = timezone.localdate()

        # 1. Subscribers
        active_subscribers = Subscriber.objects.filter(
            account_status=Subscriber.AccountStatus.ACTIVE,
            is_deleted=False,
        ).count()
        
        expired_subscribers = Subscriber.objects.filter(
            account_status=Subscriber.AccountStatus.EXPIRED,
            is_deleted=False,
        ).count()

        # 2. Sessions (Online Now)
        online_users = Session.objects.filter(
            state=Session.SessionState.ACTIVE
        ).count()

        # 3. Revenue
        revenue_today = (
            Subscription.objects
            .filter(activated_at__date=today)
            .aggregate(total=Sum("amount_paid_usd"))["total"] or Decimal("0.00")
        )
        
        revenue_month = (
            Subscription.objects
            .filter(
                activated_at__year=today.year,
                activated_at__month=today.month,
            )
            .aggregate(total=Sum("amount_paid_usd"))["total"] or Decimal("0.00")
        )

        # 4. Operations & Alerts
        pending_device_requests = DeviceChangeRequest.objects.filter(
            status=DeviceChangeRequest.RequestStatus.PENDING,
            is_deleted=False,
        ).count()

        quota_violations = DailyQuotaUsage.objects.filter(
            usage_date=today,
            is_exceeded=True,
        ).count()

        fraud_alerts = FraudAlert.objects.filter(
            status=FraudAlert.Status.OPEN
        ).count()

        # Return exact shape expected by frontend ADMIN_STATS mock
        return Response({
            "activeSubscribers": active_subscribers,
            "expiredSubscribers": expired_subscribers,
            "onlineUsers": online_users,
            "revenueToday": float(revenue_today),
            "revenueMonth": float(revenue_month),
            "pendingDeviceRequests": pending_device_requests,
            "quotaViolations": quota_violations,
            "fraudAlerts": fraud_alerts,
        })


class RevenueSummaryViewSet(ReadOnlyModelViewSet):
    """
    Revenue reporting.

    list:     GET /api/reporting/revenue/
    retrieve: GET /api/reporting/revenue/{id}/
    current_month: GET /api/reporting/revenue/current-month/
    """

    permission_classes = [IsAuthenticated, IsAdminUser]
    filter_backends = [filters.OrderingFilter]
    ordering_fields = ["summary_date", "monthly_revenue"]
    ordering = ["-summary_date"]

    def get_queryset(self):
        qs = RevenueSummary.objects.all()
        start = self.request.query_params.get("start_date")
        end = self.request.query_params.get("end_date")
        if start:
            qs = qs.filter(summary_date__gte=start)
        if end:
            qs = qs.filter(summary_date__lte=end)
        return qs

    def get_serializer_class(self):
        if self.action == "list":
            return RevenueSummaryListSerializer
        return RevenueSummarySerializer

    @action(detail=False, methods=["get"], url_path="current-month")
    def current_month(self, request):
        """GET /api/reporting/revenue/current-month/ — current month's revenue snapshot."""
        today = timezone.localdate()
        summary = RevenueSummary.objects.filter(
            summary_date__year=today.year,
            summary_date__month=today.month,
        ).order_by("-summary_date").first()

        if not summary:
            return Response(
                {"detail": "No revenue data available for the current month yet."},
                status=status.HTTP_404_NOT_FOUND,
            )
        return Response(RevenueSummarySerializer(summary).data)

    @action(detail=False, methods=["get"], url_path="live")
    def live(self, request):
        """
        GET /api/reporting/revenue/live/
        Calculates today's and this month's revenue directly from subscriptions.
        """
        from django.db.models import Sum
        from apps.subscriptions.models import Subscription
        from decimal import Decimal

        today = timezone.localdate()
        today_revenue = (
            Subscription.objects
            .filter(activated_at__date=today)
            .aggregate(total=Sum("amount_paid_usd"))["total"] or Decimal("0.00")
        )
        month_revenue = (
            Subscription.objects
            .filter(
                activated_at__year=today.year,
                activated_at__month=today.month,
            )
            .aggregate(total=Sum("amount_paid_usd"))["total"] or Decimal("0.00")
        )

        return Response(
            {
                "today": today_revenue,
                "this_month": month_revenue,
                "currency": "USD",
                "as_of": timezone.now(),
            }
        )


class SubscriberReportViewSet(ReadOnlyModelViewSet):
    """
    Per-subscriber usage and spend reports.

    list:     GET /api/reporting/subscriber-reports/
    retrieve: GET /api/reporting/subscriber-reports/{id}/
    generate: POST /api/reporting/subscriber-reports/generate/
    """

    permission_classes = [IsAuthenticated, IsAdminUser]
    filter_backends = [filters.OrderingFilter]
    ordering_fields = ["generated_at", "total_gb", "total_spent_usd"]
    ordering = ["-generated_at"]

    def get_queryset(self):
        qs = SubscriberReport.objects.select_related("subscriber")
        serializer = ReportingFilterSerializer(data=self.request.query_params)
        if not serializer.is_valid():
            return qs

        data = serializer.validated_data
        if data.get("subscriber_id"):
            qs = qs.filter(subscriber_id=data["subscriber_id"])
        if data.get("start_date"):
            qs = qs.filter(report_period_start__gte=data["start_date"])
        if data.get("end_date"):
            qs = qs.filter(report_period_end__lte=data["end_date"])
        if data.get("status_filter") == "sent":
            qs = qs.filter(is_sent=True)
        elif data.get("status_filter") == "not_sent":
            qs = qs.filter(is_sent=False)

        return qs

    def get_serializer_class(self):
        if self.action == "list":
            return SubscriberReportListSerializer
        return SubscriberReportDetailSerializer

    @action(detail=False, methods=["post"], url_path="generate")
    def generate(self, request):
        """
        POST /api/reporting/subscriber-reports/generate/
        Body: { "subscriber_id": "<uuid>", "start_date": "2026-06-01", "end_date": "2026-06-30" }
        Queues a report generation task for the specified subscriber and period.
        """
        subscriber_id = request.data.get("subscriber_id")
        start_date = request.data.get("start_date")
        end_date = request.data.get("end_date")

        errors = {}
        if not subscriber_id:
            errors["subscriber_id"] = "This field is required."
        if not start_date:
            errors["start_date"] = "This field is required."
        if not end_date:
            errors["end_date"] = "This field is required."
        if errors:
            return Response(errors, status=status.HTTP_400_BAD_REQUEST)

        # Validate subscriber exists
        from apps.subscribers.models import Subscriber
        try:
            Subscriber.objects.get(id=subscriber_id, is_deleted=False)
        except (Subscriber.DoesNotExist, Exception):
            return Response(
                {"subscriber_id": "Subscriber not found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        from .tasks import generate_subscriber_report
        generate_subscriber_report.delay(
            subscriber_id=str(subscriber_id),
            start_date=str(start_date),
            end_date=str(end_date),
        )

        return Response(
            {"detail": "Report generation queued. It will be available shortly."},
            status=status.HTTP_202_ACCEPTED,
        )


class BandwidthUsageReportView(APIView):
    """
    GET /api/reporting/bandwidth/
    Returns bandwidth usage aggregated by subscriber and plan tier.
    Query params: ?start_date=2026-06-01&end_date=2026-06-30
    """

    permission_classes = [IsAuthenticated, IsAdminUser]

    def get(self, request, *args, **kwargs):
        from django.db.models import Sum, Count
        from apps.accounting.models import Session

        start_date = request.query_params.get("start_date")
        end_date = request.query_params.get("end_date")

        qs = Session.objects.filter(state=Session.SessionState.CLOSED)
        if start_date:
            qs = qs.filter(started_at__date__gte=start_date)
        if end_date:
            qs = qs.filter(started_at__date__lte=end_date)

        totals = qs.aggregate(
            total_upload_bytes=Sum("upload_bytes"),
            total_download_bytes=Sum("download_bytes"),
            total_sessions=Count("id"),
        )

        # Convert to GB
        gb = 1024 ** 3
        return Response(
            {
                "total_upload_gb": round((totals["total_upload_bytes"] or 0) / gb, 3),
                "total_download_gb": round((totals["total_download_bytes"] or 0) / gb, 3),
                "total_sessions": totals["total_sessions"],
                "period": {"start": start_date, "end": end_date},
            }
        )