# Generated by Django 5.2.15 on 2026-06-11 12:25

import django.core.validators
import django.db.models.deletion
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('username', models.CharField(help_text='Used for captive portal and RADIUS authentication.', max_length=32, unique=True, validators=[utils.validators.validate_subscriber_username], verbose_name='Username')),
                ('phone_number', models.CharField(help_text='Used for WhatsApp notifications.', max_length=20, unique=True, validators=[utils.validators.validate_zimbabwe_phone], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('national_id', models.CharField(blank=True, help_text='Optional. Zimbabwean National ID format: 63-123456-A-75.', max_length=20, validators=[utils.validators.validate_zimbabwe_national_id], verbose_name='National ID')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('pending', 'Pending Activation'), ('banned', 'Banned')], db_index=True, default='pending', max_length=20, verbose_name='Account Status')),
                ('suspension_reason', models.TextField(blank=True, help_text='Populated when account is suspended or banned.', verbose_name='Suspension Reason')),
                ('radius_password', models.CharField(help_text='Never store plaintext. Use set_radius_password().', max_length=255, verbose_name='RADIUS Password (hashed)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'db_table': 'subscribers_subscriber',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['username'], name='idx_subscriber_username'), models.Index(fields=['phone_number'], name='idx_subscriber_phone'), models.Index(fields=['account_status'], name='idx_subscriber_status')],
            },
        ),
    ]
