# Generated by Django 5.2.15 on 2026-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='admin_users', related_query_name='admin_user', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='admin_users', related_query_name='admin_user', to='auth.permission', verbose_name='User Permissions'),
        ),
    ]
