# Generated by Django 5.2.15 on 2026-06-11 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metrics_date', models.DateField(db_index=True, unique=True, verbose_name='Metrics Date')),
                ('total_subscribers', models.PositiveIntegerField(default=0, verbose_name='Total Subscribers')),
                ('active_subscribers', models.PositiveIntegerField(default=0, verbose_name='Active Subscribers')),
                ('expired_subscribers', models.PositiveIntegerField(default=0, verbose_name='Expired Subscribers')),
                ('suspended_subscribers', models.PositiveIntegerField(default=0, verbose_name='Suspended Subscribers')),
                ('new_subscribers_today', models.PositiveIntegerField(default=0, verbose_name='New Today')),
                ('churned_subscribers', models.PositiveIntegerField(default=0, verbose_name='Churned (Expired)')),
                ('online_now', models.PositiveIntegerField(default=0, verbose_name='Online Now')),
                ('sessions_today', models.PositiveIntegerField(default=0, verbose_name='Sessions Today')),
                ('avg_session_minutes', models.FloatField(default=0.0, verbose_name='Avg Session Duration (minutes)')),
                ('total_upload_gb', models.FloatField(default=0.0, verbose_name='Total Upload (GB)')),
                ('total_download_gb', models.FloatField(default=0.0, verbose_name='Total Download (GB)')),
                ('total_traffic_gb', models.FloatField(default=0.0, verbose_name='Total Traffic (GB)')),
                ('peak_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Peak Hour (0-23)')),
                ('quota_exceeded_count', models.PositiveIntegerField(default=0, verbose_name='Quota Exceeded')),
                ('quota_warned_count', models.PositiveIntegerField(default=0, verbose_name='Quota Warnings')),
                ('revenue_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Revenue (USD)')),
                ('new_plans_sold', models.PositiveIntegerField(default=0, verbose_name='New Plans Sold')),
                ('renewals_today', models.PositiveIntegerField(default=0, verbose_name='Renewals')),
                ('vouchers_redeemed', models.PositiveIntegerField(default=0, verbose_name='Vouchers Redeemed')),
                ('failed_logins', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('fraud_alerts', models.PositiveIntegerField(default=0, verbose_name='Fraud Alerts Triggered')),
                ('system_errors', models.PositiveIntegerField(default=0, verbose_name='System Errors')),
                ('unique_devices', models.PositiveIntegerField(default=0, verbose_name='Unique Devices')),
                ('device_changes_requested', models.PositiveIntegerField(default=0, verbose_name='Device Changes Requested')),
                ('admin_actions_today', models.PositiveIntegerField(default=0, verbose_name='Admin Actions')),
            ],
            options={
                'verbose_name': 'Dashboard Metrics',
                'verbose_name_plural': 'Dashboard Metrics',
                'db_table': 'reporting_dashboard_metrics',
                'ordering': ['-metrics_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('summary_date', models.DateField(verbose_name='Month (first day)')),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Daily Revenue')),
                ('weekly_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Weekly Revenue')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Revenue')),
                ('daily_plan_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Daily Plans Revenue')),
                ('weekly_plan_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Weekly Plans Revenue')),
                ('monthly_plan_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Plans Revenue')),
                ('custom_plan_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custom Plans Revenue')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Total Transactions')),
                ('successful_transactions', models.PositiveIntegerField(default=0, verbose_name='Successful Transactions')),
                ('failed_transactions', models.PositiveIntegerField(default=0, verbose_name='Failed Transactions')),
                ('new_subscriptions', models.PositiveIntegerField(default=0, verbose_name='New Subscriptions')),
                ('renewed_subscriptions', models.PositiveIntegerField(default=0, verbose_name='Renewed Subscriptions')),
                ('cancelled_subscriptions', models.PositiveIntegerField(default=0, verbose_name='Cancelled Subscriptions')),
            ],
            options={
                'verbose_name': 'Revenue Summary',
                'verbose_name_plural': 'Revenue Summaries',
                'db_table': 'reporting_revenue_summary',
                'ordering': ['-summary_date'],
                'unique_together': {('summary_date',)},
            },
        ),
        migrations.CreateModel(
            name='SubscriberReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_period_start', models.DateField(verbose_name='Period Start')),
                ('report_period_end', models.DateField(verbose_name='Period End')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='Sessions')),
                ('total_session_hours', models.FloatField(default=0.0, verbose_name='Total Hours Online')),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Active')),
                ('upload_gb', models.FloatField(default=0.0, verbose_name='Upload (GB)')),
                ('download_gb', models.FloatField(default=0.0, verbose_name='Download (GB)')),
                ('total_gb', models.FloatField(default=0.0, verbose_name='Total (GB)')),
                ('quota_limit_gb', models.FloatField(blank=True, null=True, verbose_name='Quota Limit (GB)')),
                ('quota_usage_percent', models.FloatField(default=0.0, verbose_name='Quota Usage (%)')),
                ('plans_active', models.PositiveIntegerField(default=0, verbose_name='Active Plans')),
                ('renewals_count', models.PositiveIntegerField(default=0, verbose_name='Renewals')),
                ('total_spent_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Spent')),
                ('quota_warnings', models.PositiveIntegerField(default=0, verbose_name='Quota Warnings')),
                ('failed_logins', models.PositiveIntegerField(default=0, verbose_name='Failed Logins')),
                ('fraud_alerts', models.PositiveIntegerField(default=0, verbose_name='Fraud Alerts')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent to User')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='subscribers.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Subscriber Report',
                'verbose_name_plural': 'Subscriber Reports',
                'db_table': 'reporting_subscriber_report',
                'ordering': ['-report_period_end'],
            },
        ),
    ]
