# Generated by Django 5.2.15 on 2026-06-11 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site_name', models.CharField(default='TengarakoData', max_length=100, verbose_name='Site Name')),
                ('site_url', models.URLField(help_text='Public URL where users access the portal.', verbose_name='Portal URL')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('header_text', models.CharField(blank=True, max_length=255, verbose_name='Header Text')),
                ('footer_text', models.CharField(blank=True, max_length=255, verbose_name='Footer Text')),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, verbose_name='Primary Color (Hex)')),
                ('secondary_color', models.CharField(default='#1e40af', max_length=7, verbose_name='Secondary Color (Hex)')),
                ('session_timeout_minutes', models.PositiveSmallIntegerField(default=1440, verbose_name='Session Timeout (minutes)')),
                ('allow_remember_me', models.BooleanField(default=True, verbose_name='Allow Remember Me')),
                ('require_email', models.BooleanField(default=False, verbose_name='Require Email')),
                ('require_phone', models.BooleanField(default=False, verbose_name='Require Phone')),
                ('show_terms', models.BooleanField(default=True, verbose_name='Show Terms & Conditions')),
                ('terms_text', models.TextField(blank=True, verbose_name='Terms & Conditions')),
                ('terms_version', models.CharField(default='1.0', max_length=20, verbose_name='Terms Version')),
            ],
            options={
                'verbose_name': 'Portal Configuration',
                'verbose_name_plural': 'Portal Configurations',
                'db_table': 'captive_portal_config',
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_key', models.CharField(max_length=64, unique=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Device MAC')),
                ('logged_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged In At')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('logged_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Logged Out At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('logout_reason', models.CharField(blank=True, help_text="E.g. 'manual', 'timeout', 'subscription_expired'.", max_length=100, verbose_name='Logout Reason')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='subscribers.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Portal Session',
                'verbose_name_plural': 'Portal Sessions',
                'db_table': 'captive_portal_session',
                'ordering': ['-logged_in_at'],
                'indexes': [models.Index(fields=['subscriber', '-logged_in_at'], name='idx_portal_sub_date'), models.Index(fields=['is_active'], name='idx_portal_active')],
            },
        ),
    ]
