# Generated by Django 5.2.15 on 2026-06-11 12:26

import apps.vouchers.models
import django.db.models.deletion
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="Descriptive label, e.g. 'June 2026 Monthly 50GB'.", max_length=120, verbose_name='Batch Name')),
                ('quantity', models.PositiveIntegerField(help_text='Number of voucher codes to generate.', validators=[utils.validators.validate_positive_integer], verbose_name='Quantity')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no expiry date on unredeemed codes.', null=True, verbose_name='Valid Until')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_batches', to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_batches', to='subscriptions.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Voucher Batch',
                'verbose_name_plural': 'Voucher Batches',
                'db_table': 'vouchers_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(default=apps.vouchers.models._generate_voucher_code, max_length=14, unique=True, validators=[utils.validators.validate_voucher_code], verbose_name='Voucher Code')),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('voided', 'Voided')], db_index=True, default='unused', max_length=20, verbose_name='Status')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Redeemed At')),
                ('void_reason', models.TextField(blank=True, verbose_name='Void Reason')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_vouchers', to='subscribers.subscriber', verbose_name='Redeemed By')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Voided By')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.voucherbatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'db_table': 'vouchers_voucher',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='idx_voucher_code'), models.Index(fields=['status'], name='idx_voucher_status')],
            },
        ),
    ]
