# Generated by Django 5.2.15 on 2026-06-11 12:25

import django.db.models.deletion
import utils.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mac_address', models.CharField(help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, unique=True, validators=[utils.validators.validate_mac_address], verbose_name='MAC Address')),
                ('device_name', models.CharField(blank=True, help_text="Optional label, e.g. 'Samsung Galaxy A54'.", max_length=100, verbose_name='Device Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('replaced', 'Replaced'), ('revoked', 'Revoked (Fraud)'), ('pending', 'Pending Approval')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('is_primary', models.BooleanField(db_index=True, default=True, help_text='Only the primary device is used for RADIUS MAC authentication.', verbose_name='Primary Device')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='First Seen')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Seen')),
                ('registered_by', models.ForeignKey(blank=True, help_text='Null when auto-registered on first login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_devices', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='subscribers.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices_device',
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('new_mac_address', models.CharField(max_length=17, validators=[utils.validators.validate_mac_address], verbose_name='Requested New MAC Address')),
                ('new_device_name', models.CharField(blank=True, max_length=100, verbose_name='New Device Name')),
                ('reason', models.CharField(choices=[('lost', 'Phone Lost'), ('stolen', 'Phone Stolen'), ('new_device', 'New Phone Purchased'), ('laptop', 'Laptop Replacement'), ('other', 'Other')], max_length=20, verbose_name='Reason for Change')),
                ('reason_detail', models.TextField(blank=True, verbose_name='Additional Details')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Request Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('old_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_change_requests', to='devices.device', verbose_name='Current Device')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_device_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_change_requests', to='subscribers.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Device Change Request',
                'verbose_name_plural': 'Device Change Requests',
                'db_table': 'devices_change_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mac_address'], name='idx_device_mac'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['subscriber', 'is_primary'], name='idx_device_subscriber_primary'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'active')), fields=('subscriber',), name='uq_one_primary_device_per_subscriber'),
        ),
    ]
