# Generated by Django 5.2.15 on 2026-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='browser_fingerprint',
            field=models.CharField(blank=True, help_text='Hash to prevent MAC spoofing.', max_length=64, verbose_name='Browser Fingerprint'),
        ),
        migrations.AddField(
            model_name='device',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
    ]
