# Generated by Django 5.2.15 on 2026-06-11 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Rule Name')),
                ('rule_type', models.CharField(choices=[('multiple_mac', 'Multiple MAC Addresses'), ('concurrent_sessions', 'Concurrent Sessions'), ('repeated_login_failures', 'Repeated Login Failures'), ('geographic_anomaly', 'Geographic Anomaly'), ('excessive_data', 'Excessive Data Consumption'), ('suspicious_device_change', 'Suspicious Device Change'), ('throttled_bypass', 'Throttle Bypass Attempt'), ('credential_sharing', 'Credential Sharing')], db_index=True, max_length=50, verbose_name='Rule Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, verbose_name='Severity Level')),
                ('threshold_value', models.PositiveIntegerField(blank=True, help_text='Context-dependent: count, time minutes, GB, etc.', null=True, verbose_name='Threshold Value')),
                ('time_window_minutes', models.PositiveSmallIntegerField(default=60, help_text='Window for detecting pattern.', verbose_name='Time Window (minutes)')),
                ('auto_trigger_action', models.CharField(choices=[('alert', 'Alert only'), ('throttle', 'Throttle speed'), ('block', 'Block access'), ('suspend', 'Suspend account')], default='alert', max_length=50, verbose_name='Auto-Trigger Action')),
                ('require_admin_review', models.BooleanField(default=True, help_text='If true, action taken only after manual approval.', verbose_name='Require Admin Review')),
            ],
            options={
                'verbose_name': 'Fraud Detection Rule',
                'verbose_name_plural': 'Fraud Detection Rules',
                'db_table': 'fraud_rule',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('whitelisted', 'Whitelisted')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], verbose_name='Severity')),
                ('evidence', models.JSONField(default=dict, help_text='Structured data supporting the alert (IPs, MACs, timestamps, etc.).', verbose_name='Evidence')),
                ('description', models.TextField(verbose_name='Alert Description')),
                ('resolution', models.CharField(blank=True, choices=[('benign', 'Benign Behavior'), ('user_error', 'User Error'), ('account_compromised', 'Account Compromised'), ('system_issue', 'System Issue'), ('policy_adjustment', 'Policy Needs Adjustment')], max_length=50, null=True, verbose_name='Resolution')),
                ('investigation_notes', models.TextField(blank=True, verbose_name='Investigation Notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('action_taken', models.CharField(blank=True, help_text="E.g. 'throttled', 'suspended', 'device_revoked'.", max_length=50, verbose_name='Action Taken')),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_fraud_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Investigated By')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='subscribers.subscriber', verbose_name='Subscriber')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='fraud.fraudrule', verbose_name='Triggered Rule')),
            ],
            options={
                'verbose_name': 'Fraud Alert',
                'verbose_name_plural': 'Fraud Alerts',
                'db_table': 'fraud_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscriber', '-created_at'], name='idx_fraud_sub_date'), models.Index(fields=['status'], name='idx_fraud_status'), models.Index(fields=['severity'], name='idx_fraud_severity')],
            },
        ),
    ]
