# Generated by Django 5.2.15 on 2026-06-11 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acctuniqueid', models.CharField(help_text='Unique session identifier from FreeRADIUS.', max_length=64, unique=True, verbose_name='Accounting Unique ID')),
                ('username', models.CharField(db_index=True, max_length=64, verbose_name='Username')),
                ('realm', models.CharField(blank=True, max_length=64, verbose_name='Realm')),
                ('nasipaddress', models.GenericIPAddressField(help_text='IP of the TP-Link EAP110 access point.', verbose_name='NAS IP Address')),
                ('nasportid', models.CharField(blank=True, max_length=32, verbose_name='NAS Port ID')),
                ('nasporttype', models.CharField(blank=True, max_length=32, verbose_name='NAS Port Type')),
                ('acctstarttime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Session Start Time')),
                ('acctstoptime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Session Stop Time')),
                ('acctsessiontime', models.BigIntegerField(default=0, verbose_name='Session Duration (seconds)')),
                ('acctauthentic', models.CharField(blank=True, max_length=32, verbose_name='Auth Method')),
                ('acctstatustype', models.CharField(choices=[('Start', 'Session Start'), ('Stop', 'Session Stop'), ('Alive', 'Interim Update')], max_length=32, verbose_name='Status Type')),
                ('acctinputoctets', models.BigIntegerField(default=0, verbose_name='Input (Upload) Bytes')),
                ('acctoutputoctets', models.BigIntegerField(default=0, verbose_name='Output (Download) Bytes')),
                ('calledstationid', models.CharField(blank=True, max_length=50, verbose_name='Called Station ID (AP MAC)')),
                ('callingstationid', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Calling Station ID (Client MAC)')),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP Address')),
                ('acctterminatecause', models.CharField(blank=True, max_length=32, verbose_name='Terminate Cause')),
                ('servicetype', models.CharField(blank=True, max_length=32, verbose_name='Service Type')),
                ('framedprotocol', models.CharField(blank=True, max_length=32, verbose_name='Framed Protocol')),
                ('connectinfo_start', models.TextField(blank=True, verbose_name='Connect Info (Start)')),
                ('connectinfo_stop', models.TextField(blank=True, verbose_name='Connect Info (Stop)')),
            ],
            options={
                'verbose_name': 'RADIUS Accounting Record',
                'verbose_name_plural': 'RADIUS Accounting Records',
                'db_table': 'radacct',
                'ordering': ['-acctstarttime'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=17, verbose_name='Device MAC')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP')),
                ('state', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('interrupted', 'Interrupted (No Stop packet received)')], db_index=True, default='active', max_length=20, verbose_name='Session State')),
                ('started_at', models.DateTimeField(verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('duration_seconds', models.BigIntegerField(default=0, verbose_name='Duration (seconds)')),
                ('upload_bytes', models.BigIntegerField(default=0, verbose_name='Upload (bytes)')),
                ('download_bytes', models.BigIntegerField(default=0, verbose_name='Download (bytes)')),
                ('terminate_cause', models.CharField(blank=True, max_length=64, verbose_name='Terminate Cause')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'accounting_session',
                'ordering': ['-started_at'],
            },
        ),
    ]
