# Generated by Django 5.2.15 on 2026-06-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusaccounting',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_sessions', to='subscribers.subscriber', verbose_name='Subscriber'),
        ),
        migrations.AddField(
            model_name='session',
            name='radius_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='accounting.radiusaccounting', verbose_name='RADIUS Record'),
        ),
        migrations.AddField(
            model_name='session',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='subscribers.subscriber', verbose_name='Subscriber'),
        ),
        migrations.AddIndex(
            model_name='radiusaccounting',
            index=models.Index(fields=['username', 'acctstarttime'], name='idx_radacct_user_start'),
        ),
        migrations.AddIndex(
            model_name='radiusaccounting',
            index=models.Index(fields=['callingstationid'], name='idx_radacct_mac'),
        ),
        migrations.AddIndex(
            model_name='radiusaccounting',
            index=models.Index(fields=['acctstoptime'], name='idx_radacct_stop'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['subscriber', 'started_at'], name='idx_session_sub_start'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['state'], name='idx_session_state'),
        ),
    ]
