# Generated by Django 5.2.15 on 2026-06-11 12:26

import django.db.models.deletion
import utils.validators
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandwidth', '0001_initial'),
        ('quota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan Name')),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20, verbose_name='Plan Type')),
                ('duration_days', models.PositiveIntegerField(help_text='Number of calendar days the plan is valid.', validators=[utils.validators.validate_positive_integer], verbose_name='Duration (Days)')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8, validators=[utils.validators.validate_positive_decimal], verbose_name='Price (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Available for Purchase')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('grace_period_hours', models.PositiveSmallIntegerField(default=0, help_text='Hours of continued access after expiry before the account is fully blocked. Set to 0 for immediate cutoff.', verbose_name='Grace Period (Hours)')),
                ('bandwidth_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='bandwidth.bandwidthprofile', verbose_name='Bandwidth Profile')),
                ('quota_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='quota.quotapolicy', verbose_name='Daily Quota Policy')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'subscriptions_plan',
                'ordering': ['plan_type', 'price_usd'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('grace', 'In Grace Period')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('activated_at', models.DateTimeField(verbose_name='Activated At')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Grace Period Ends At')),
                ('amount_paid_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Amount Paid (USD)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions_subscription',
                'ordering': ['-activated_at'],
            },
        ),
    ]
