/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriberRouteImport } from './routes/subscriber'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriberIndexRouteImport } from './routes/subscriber.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SubscriberUsageRouteImport } from './routes/subscriber.usage'
import { Route as SubscriberRenewRouteImport } from './routes/subscriber.renew'
import { Route as SubscriberDeviceRouteImport } from './routes/subscriber.device'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'

const SubscriberRoute = SubscriberRouteImport.update({
  id: '/subscriber',
  path: '/subscriber',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriberIndexRoute = SubscriberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscriberRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SubscriberUsageRoute = SubscriberUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SubscriberRoute,
} as any)
const SubscriberRenewRoute = SubscriberRenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => SubscriberRoute,
} as any)
const SubscriberDeviceRoute = SubscriberDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => SubscriberRoute,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/subscriber': typeof SubscriberRouteWithChildren
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/subscriber/device': typeof SubscriberDeviceRoute
  '/subscriber/renew': typeof SubscriberRenewRoute
  '/subscriber/usage': typeof SubscriberUsageRoute
  '/admin/': typeof AdminIndexRoute
  '/subscriber/': typeof SubscriberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/subscriber/device': typeof SubscriberDeviceRoute
  '/subscriber/renew': typeof SubscriberRenewRoute
  '/subscriber/usage': typeof SubscriberUsageRoute
  '/admin': typeof AdminIndexRoute
  '/subscriber': typeof SubscriberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/subscriber': typeof SubscriberRouteWithChildren
  '/admin/plans': typeof AdminPlansRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/subscriber/device': typeof SubscriberDeviceRoute
  '/subscriber/renew': typeof SubscriberRenewRoute
  '/subscriber/usage': typeof SubscriberUsageRoute
  '/admin/': typeof AdminIndexRoute
  '/subscriber/': typeof SubscriberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/subscriber'
    | '/admin/plans'
    | '/admin/subscribers'
    | '/admin/vouchers'
    | '/subscriber/device'
    | '/subscriber/renew'
    | '/subscriber/usage'
    | '/admin/'
    | '/subscriber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/admin/plans'
    | '/admin/subscribers'
    | '/admin/vouchers'
    | '/subscriber/device'
    | '/subscriber/renew'
    | '/subscriber/usage'
    | '/admin'
    | '/subscriber'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/subscriber'
    | '/admin/plans'
    | '/admin/subscribers'
    | '/admin/vouchers'
    | '/subscriber/device'
    | '/subscriber/renew'
    | '/subscriber/usage'
    | '/admin/'
    | '/subscriber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SubscriberRoute: typeof SubscriberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriber': {
      id: '/subscriber'
      path: '/subscriber'
      fullPath: '/subscriber'
      preLoaderRoute: typeof SubscriberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriber/': {
      id: '/subscriber/'
      path: '/'
      fullPath: '/subscriber/'
      preLoaderRoute: typeof SubscriberIndexRouteImport
      parentRoute: typeof SubscriberRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/subscriber/usage': {
      id: '/subscriber/usage'
      path: '/usage'
      fullPath: '/subscriber/usage'
      preLoaderRoute: typeof SubscriberUsageRouteImport
      parentRoute: typeof SubscriberRoute
    }
    '/subscriber/renew': {
      id: '/subscriber/renew'
      path: '/renew'
      fullPath: '/subscriber/renew'
      preLoaderRoute: typeof SubscriberRenewRouteImport
      parentRoute: typeof SubscriberRoute
    }
    '/subscriber/device': {
      id: '/subscriber/device'
      path: '/device'
      fullPath: '/subscriber/device'
      preLoaderRoute: typeof SubscriberDeviceRouteImport
      parentRoute: typeof SubscriberRoute
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPlansRoute: AdminPlansRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SubscriberRouteChildren {
  SubscriberDeviceRoute: typeof SubscriberDeviceRoute
  SubscriberRenewRoute: typeof SubscriberRenewRoute
  SubscriberUsageRoute: typeof SubscriberUsageRoute
  SubscriberIndexRoute: typeof SubscriberIndexRoute
}

const SubscriberRouteChildren: SubscriberRouteChildren = {
  SubscriberDeviceRoute: SubscriberDeviceRoute,
  SubscriberRenewRoute: SubscriberRenewRoute,
  SubscriberUsageRoute: SubscriberUsageRoute,
  SubscriberIndexRoute: SubscriberIndexRoute,
}

const SubscriberRouteWithChildren = SubscriberRoute._addFileChildren(
  SubscriberRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SubscriberRoute: SubscriberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
