# Generated by Django 5.2.15 on 2026-06-11 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create_user', 'Create User'), ('delete_user', 'Delete User'), ('edit_user', 'Edit User'), ('reset_password', 'Reset Password'), ('change_role', 'Change Role'), ('suspend_subscriber', 'Suspend Subscriber'), ('activate_subscriber', 'Activate Subscriber'), ('renew_subscription', 'Renew Subscription'), ('generate_voucher', 'Generate Voucher'), ('approve_device_change', 'Approve Device Change'), ('reject_device_change', 'Reject Device Change'), ('modify_bandwidth', 'Modify Bandwidth'), ('export_data', 'Export Data'), ('bulk_operation', 'Bulk Operation')], db_index=True, max_length=50, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Action Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('affected_records_count', models.PositiveIntegerField(default=1, help_text='For bulk operations.', verbose_name='Records Affected')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribers.subscriber', verbose_name='Target Subscriber')),
            ],
            options={
                'verbose_name': 'Admin Activity',
                'verbose_name_plural': 'Admin Activities',
                'db_table': 'audit_admin_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='idx_admin_activity_date'), models.Index(fields=['action'], name='idx_admin_activity_action')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Actor IP Address')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('authenticate', 'Authentication Attempt'), ('authorize', 'Authorization Check'), ('suspend', 'Account Suspended'), ('activate', 'Account Activated'), ('reset_password', 'Password Reset'), ('export', 'Data Exported'), ('import', 'Data Imported'), ('approve', 'Approved'), ('reject', 'Rejected'), ('redeem', 'Voucher Redeemed')], db_index=True, max_length=50, verbose_name='Action')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='Object ID')),
                ('description', models.TextField(help_text='Human-readable summary of what happened.', verbose_name='Description')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dict of {field: {old, new}} for updates.', verbose_name='Field Changes')),
                ('severity', models.PositiveSmallIntegerField(choices=[(0, 'Debug'), (1, 'Info'), (2, 'Warning'), (3, 'Error'), (4, 'Critical')], db_index=True, default=1, verbose_name='Severity')),
                ('source', models.CharField(default='api', help_text="E.g. 'api', 'admin_panel', 'celery_task', 'freeradius'.", max_length=50, verbose_name='Source')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('actor_subscriber', models.ForeignKey(blank=True, help_text='If action by subscriber via captive portal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to='subscribers.subscriber', verbose_name='Actor (Subscriber)')),
                ('actor_user', models.ForeignKey(blank=True, help_text='Null if action by system or external service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to=settings.AUTH_USER_MODEL, verbose_name='Actor (Admin)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Object Type')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='idx_audit_action_date'), models.Index(fields=['actor_subscriber', '-created_at'], name='idx_audit_subscriber_date'), models.Index(fields=['actor_user', '-created_at'], name='idx_audit_admin_date'), models.Index(fields=['severity'], name='idx_audit_severity')],
            },
        ),
    ]
