# Generated by Django 5.2.15 on 2026-06-11 12:25

import utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="E.g. 'Gold 10Mbps'.", max_length=80, unique=True, verbose_name='Profile Name')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Tier')),
                ('download_mbps', models.PositiveSmallIntegerField(validators=[utils.validators.validate_bandwidth_mbps], verbose_name='Download Speed (Mbps)')),
                ('upload_mbps', models.PositiveSmallIntegerField(validators=[utils.validators.validate_bandwidth_mbps], verbose_name='Upload Speed (Mbps)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive profiles cannot be assigned to new plans.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Bandwidth Profile',
                'verbose_name_plural': 'Bandwidth Profiles',
                'db_table': 'bandwidth_profile',
                'ordering': ['download_mbps'],
            },
        ),
    ]
