# Generated by Django 5.2.15 on 2026-06-11 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('server_host', models.CharField(help_text='Hostname or IP of FreeRADIUS server.', max_length=255, verbose_name='RADIUS Server Host')),
                ('server_port', models.PositiveIntegerField(default=1812, verbose_name='Server Port')),
                ('shared_secret', models.CharField(help_text='Authentication secret between Django and FreeRADIUS. Keep secure!', max_length=255, verbose_name='Shared Secret')),
                ('accounting_port', models.PositiveIntegerField(default=1813, verbose_name='Accounting Port')),
                ('auth_timeout_seconds', models.PositiveSmallIntegerField(default=5, verbose_name='Authentication Timeout (seconds)')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='Max Retries')),
                ('accounting_enabled', models.BooleanField(default=True, verbose_name='Accounting Enabled')),
                ('interim_update_interval', models.PositiveSmallIntegerField(default=600, verbose_name='Interim Update Interval (seconds)')),
                ('allow_concurrent_sessions', models.BooleanField(default=False, verbose_name='Allow Concurrent Sessions')),
                ('max_sessions_per_user', models.PositiveSmallIntegerField(default=1, help_text='How many simultaneous logins allowed.', verbose_name='Max Sessions Per User')),
                ('session_timeout_seconds', models.PositiveIntegerField(default=86400, verbose_name='Session Timeout (seconds)')),
            ],
            options={
                'verbose_name': 'RADIUS Configuration',
                'verbose_name_plural': 'RADIUS Configurations',
                'db_table': 'radius_config',
            },
        ),
        migrations.CreateModel(
            name='RadiusReplyAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Attribute Name')),
                ('attribute_type', models.CharField(choices=[('WISPr-Bandwidth-Max-Up', 'Bandwidth Max Upload'), ('WISPr-Bandwidth-Max-Down', 'Bandwidth Max Download'), ('Session-Timeout', 'Session Timeout'), ('Idle-Timeout', 'Idle Timeout'), ('Acct-Interim-Interval', 'Accounting Interim Interval'), ('Framed-IP-Address', 'Framed IP Address'), ('Reply-Message', 'Reply Message'), ('Filter-Id', 'Filter ID'), ('Class', 'Class'), ('custom', 'Custom Attribute')], max_length=100, verbose_name='RADIUS Attribute Type')),
                ('value_template', models.TextField(help_text='Template string; use {field} syntax for variable substitution.', verbose_name='Value Template')),
                ('operator', models.CharField(choices=[(':=', 'Assign'), ('+=', 'Add'), ('==', 'Compare'), ('!=', 'Not Equal'), ('>', 'Greater Than'), ('<', 'Less Than')], default=':=', max_length=5, verbose_name='Operator')),
                ('is_reply', models.BooleanField(default=True, help_text='If False, this is a check item.', verbose_name='Reply Attribute')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower = higher priority in RADIUS reply.', verbose_name='Priority')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'RADIUS Reply Attribute',
                'verbose_name_plural': 'RADIUS Reply Attributes',
                'db_table': 'radius_reply_attribute',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
