# Generated by Django 5.2.15 on 2026-06-11 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('receive_whatsapp', models.BooleanField(default=True, verbose_name='Receive WhatsApp')),
                ('receive_sms', models.BooleanField(default=True, verbose_name='Receive SMS')),
                ('receive_email', models.BooleanField(default=True, verbose_name='Receive Email')),
                ('receive_expiry_warnings', models.BooleanField(default=True, verbose_name='Subscription Expiry Warnings')),
                ('receive_quota_warnings', models.BooleanField(default=True, verbose_name='Quota Warnings')),
                ('receive_security_alerts', models.BooleanField(default=True, verbose_name='Security Alerts')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Do not send notifications between these hours.', null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='subscribers.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notifications_preference',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('event_type', models.CharField(choices=[('welcome', 'Welcome Message'), ('subscription_activated', 'Subscription Activated'), ('subscription_renewed', 'Subscription Renewed'), ('expiry_warning_7d', 'Expiry Warning (7 days)'), ('expiry_warning_3d', 'Expiry Warning (3 days)'), ('expiry_warning_1d', 'Expiry Warning (1 day)'), ('subscription_expired', 'Subscription Expired'), ('quota_warning', 'Quota Warning (80%)'), ('quota_exceeded', 'Quota Exceeded'), ('device_change_approved', 'Device Change Approved'), ('device_change_rejected', 'Device Change Rejected'), ('payment_confirmation', 'Payment Confirmation'), ('security_alert', 'Security Alert')], db_index=True, max_length=50, verbose_name='Event Type')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App')], default='whatsapp', max_length=20, verbose_name='Primary Channel')),
                ('subject', models.CharField(blank=True, help_text='For email notifications.', max_length=200, verbose_name='Subject')),
                ('body', models.TextField(help_text='Use {variable} syntax for substitution.', verbose_name='Message Body')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Available variables for this template.', verbose_name='Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notifications_template',
                'ordering': ['event_type'],
                'unique_together': {('event_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App')], max_length=20, verbose_name='Channel')),
                ('recipient', models.CharField(help_text='Phone (WhatsApp/SMS) or email address.', max_length=100, verbose_name='Recipient')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Message Body')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed')], db_index=True, default='queued', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('external_id', models.CharField(blank=True, help_text='Message ID from WhatsApp/SMS provider.', max_length=100, verbose_name='External ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Retry Count')),
                ('event_type', models.CharField(blank=True, max_length=50, verbose_name='Event Type')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Context Data')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='subscribers.subscriber', verbose_name='Recipient')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscriber', '-created_at'], name='idx_notif_sub_date'), models.Index(fields=['status'], name='idx_notif_status'), models.Index(fields=['channel'], name='idx_notif_channel')],
            },
        ),
    ]
