# Generated by Django 5.2.15 on 2026-06-11 12:26

import apps.quota.models
import django.db.models.deletion
import utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="E.g. 'Basic 2GB Daily', 'Premium Unlimited'.", max_length=100, unique=True, verbose_name='Policy Name')),
                ('daily_quota_gb', models.FloatField(blank=True, help_text='Leave blank for unlimited quota.', null=True, validators=[utils.validators.validate_positive_integer], verbose_name='Daily Quota (GB)')),
                ('warning_threshold_percent', models.PositiveSmallIntegerField(default=80, help_text='Notify user when quota usage exceeds this percentage.', validators=[apps.quota.models.validate_warning_threshold], verbose_name='Warning Threshold (%)')),
                ('soft_limit_percent', models.PositiveSmallIntegerField(default=100, help_text='Speed reduction kicks in at this % of quota. Set >100 for overage tolerance.', validators=[apps.quota.models.validate_soft_limit], verbose_name='Soft Limit (%)')),
                ('throttle_speed_mbps', models.PositiveSmallIntegerField(blank=True, help_text='Speed limit when soft limit exceeded. Null = block access.', null=True, verbose_name='Throttle Speed (Mbps)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Quota Policy',
                'verbose_name_plural': 'Quota Policies',
                'db_table': 'quota_policy',
                'ordering': ['daily_quota_gb'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuotaUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('usage_date', models.DateField(db_index=True, help_text='Calendar date in UTC.', verbose_name='Usage Date (UTC)')),
                ('upload_gb', models.FloatField(default=0.0, verbose_name='Upload (GB)')),
                ('download_gb', models.FloatField(default=0.0, verbose_name='Download (GB)')),
                ('total_gb', models.FloatField(db_index=True, default=0.0, verbose_name='Total (GB)')),
                ('quota_limit_gb', models.FloatField(blank=True, help_text='Snapshot of quota limit on this date.', null=True, verbose_name='Quota Limit (GB)')),
                ('is_exceeded', models.BooleanField(db_index=True, default=False, verbose_name='Quota Exceeded')),
                ('throttled', models.BooleanField(default=False, help_text='True if soft limit was triggered.', verbose_name='Speed Throttled')),
                ('blocked', models.BooleanField(default=False, help_text='True if hard limit triggered and no throttle configured.', verbose_name='Access Blocked')),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Warning Notification Sent')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quota_usage', to='subscribers.subscriber', verbose_name='Subscriber')),
                ('quota_policy', models.ForeignKey(blank=True, help_text='Snapshot of policy active on this date.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quota.quotapolicy', verbose_name='Applied Quota Policy')),
            ],
            options={
                'verbose_name': 'Daily Quota Usage',
                'verbose_name_plural': 'Daily Quota Usage',
                'db_table': 'quota_daily_usage',
                'ordering': ['-usage_date'],
                'indexes': [models.Index(fields=['subscriber', '-usage_date'], name='idx_quota_sub_date'), models.Index(fields=['is_exceeded'], name='idx_quota_exceeded')],
                'unique_together': {('subscriber', 'usage_date')},
            },
        ),
    ]
